### ISSUE TITLE
The dataset link is broken

### ISSUE THREAD

**Issue by whwjdqls** [leolyliu/CORE4D-Instructions#1]
Hi great work, 

I think the dataset link is broken

Thanks.

**Comment by leolyliu** [comment]
Hi, whwjdqls:

We are sorry about that. We will fix it in these two days.

**Comment by leolyliu** [comment]
We have updated ```object_models```, ```human_object_motions```, ```camera_parameters```, ```egocentric_RGB_videos``` for ```CORE4D_Real```. Other files are still processing due to their large scale.

**Comment by whwjdqls** [comment]
Thanks, it'll be great if you leave a comment when the large files are done. 
 
Great work.

**Comment by leolyliu** [comment]
@whwjdqls All the data files are updated. Sorry for the delay.
